export const SET_MEETUPS = 'SET_MEETUPS';
export const SET_MEETUP = 'SET_MEETUP';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_THREADS = 'SET_THREADS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_USER = 'SET_USER';
export const SET_IS_AUTH_RESOLVED = 'SET_IS_AUTH_RESOLVED';
export const SET_MEETUP_TO_AUTH_USER = 'SET_MEETUP_TO_AUTH_USER';
export const ADD_USERS_TO_MEETUP = 'ADD_USERS_TO_MEETUP';
export const ADD_THREAD_TO_THREADS = 'ADD_THREAD_TO_THREADS';
export const SAVE_POST_TO_THREAD = 'SAVE_POST_TO_THREAD';
export const SET_STATS_STATE = 'SET_STATS_STATE';
export const SET_META_DATA = 'SET_META_DATA';



